language: java
script:
- gradle build
deploy:
  provider: heroku
  api_key:
    secure: s/F4TQtKECzo8NMZHEBq69nkh/JXG+8qFePgKM+EvbWVXNoIwtpnPbNr5ZTsGcsrTlzka5Jbmb7ptF4Vtd+HO3F5QLfKyZYtxS/GUezC+jWawFUaJT7r8jvazOkNiF8ZdcHmh7nI0a3/xoUoLefvZFtDAFKcptkKFeLX4bpwmod4sYwVov+axn4epb0NC03Dm4B87SiaqCH4mZ2rn9682yly4bxomEJdM7otFlp6PwnqpVulaSe+SBmHQHBrJ2wWvhJutlwNND+q/CKuCTgxjN2EgBsqsqiXLXGkJEzBaEqE51gpqnXnYnpWvXhPk4d+qEIqB3Dv1vsXMGcCip7OI8TKjbawIuc2BLrzEa+rV6IoGjPqnpHKNilwyk6wivnLYayD3Syf1HykCDjkfOadpJ9iX1xrblYEXyTgBNBhI1mYhc8NaHSRsHou30+VBMxM048QvOaA+cyNIEctsmvLMk7Mo70tNoakWlBXP6bAM4FSqtT+3Rc45satk8+nTS9GuxiggXnF1zqOcJ5eVUeFbAtWg/G1iV7gUayDCWQvPhHdD5fZ+lRVYHEAqmad8SqA4LeU9L9iW7JScPGFfjuJ81QY/4tAI060CxUh15NVB2uonyWff/jyMSxLRl6j/UF9pZKsA7B0xMhi6P1oEEiv8PKBM7yh3fzQGHPwCPtIrMI=
  app: petadoptionapp-backend-05
